apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: InferencePool
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/managed-by: kustomize
  name: llmserverpool-sample
spec:
  serviceRefs:
  - gemini-jetstream-tpu-v5e-service
  - gemini-vllm-a100-service
